env:
    MANIFEST: https://github.com/mitmac29/android.git
    MANIFEST_BRANCH: crd-11.0
    DEVICE: lavender
    OEM: xiaomi
    DT_LINK: https://github.com/mitmac29/device_xiaomi_lavender1.git -b arc
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/mitmac29/vendor_xiaomi_lavender.git -b 11
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/mitmac29/kernel_xiaomi_lavender.git -b qti-oldcam
    PLATFORM: sdm660
    KT_PATH: kernel/$OEM/$DEVICE
    LUNCH_COMBO: lineage_lavender-userdebug
    TARGET: bacon
    OUTPUT: Arc*.zip

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "AOSP Build"
  trigger_type: manual
  timeout_in: 300m 
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh
